import type { Metadata } from "next";
import "@/app/globals.css";
import { ILayoutProps } from "@/types/layout.props";

export const metadata: Metadata = {
	title: "AUTH",
	description: "Generated by create next app",
};

export default function AuthLayout(
	{children}: Readonly<ILayoutProps>
) {
	
	return (
		<div className='app-bg-primary h-full flex items-center justify-center'>
			{ children }
		</div>
	);
}
