import type { Metadata } from "next";
import "@/app/globals.css";
import { ILayoutProps } from "@/types/layout.props";

export const metadata: Metadata = {
	title: "AUTH",
	description: "Generated by create next app",
};

export default function AuthLayout(
	{children}: Readonly<ILayoutProps>
) {
	
	return (
		<div className="h-full flex items-center justify-center
			bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800"
		>
			{ children }
		</div>
	);
}
