import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import { ILayoutProps } from '@/types/layout.props'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from 'sonner'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = async ({children}: Readonly<ILayoutProps>) => {
	const session = await auth()
	
	return (
		<SessionProvider session={ session }>
			<html lang="en">
			<body className={ inter.className }>{ children }</body>
			<Toaster />
			</html>
		</SessionProvider>
	)
}

export default RootLayout
